# Generated by Django 4.1.4 on 2022-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_post_tag'),
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='article.tag'),
        ),
    ]
