# Generated by Django 4.1.4 on 2022-12-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_post_tag'),
        ('account', '0003_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark',
            field=models.ManyToManyField(to='article.post'),
        ),
    ]
