# Generated by Django 4.1.4 on 2022-12-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
