# Generated by Django 4.1.4 on 2022-12-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_tag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
