# Generated by Django 4.1.4 on 2022-12-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
